packages:
  - pkgs/*
  - pkgs/parser/pkg
  - pkgs/types/pkgs/ts
  - subs/*/pkgs/*

onlyBuiltDependencies:
  - "@tailwindcss/oxide"
  - "@vscode/vsce-sign"
  - esbuild
  - keytar
  - sharp
  - workerd

overrides:
  "@mindrig/parser-wasm": workspace:*
  "@mindrig/types": workspace:*
  "@wrkspc/vsc-sync": workspace:*
  "@wrkspc/vsc-types": workspace:*
