packages:
  - pkgs/*
  - pkgs/parser/pkg
  - pkgs/types/pkgs/ts
  - subs/*/pkgs/*

onlyBuiltDependencies:
  - '@tailwindcss/oxide'
  - '@vscode/vsce-sign'
  - es5-ext
  - esbuild
  - keytar
  - sharp
  - ttf2woff2
  - workerd

overrides:
  '@wrkspc/core': workspace:*
  'react-upgrade': workspace:*
