packages:
  - vscode/extension
  - vscode/webview
  - vscode/types
  - vscode/sync
  - parser
  - parser/pkg
  - types
  - types/pkg/ts
  - pkgs/*
  - subs/*/pkgs/*

onlyBuiltDependencies:
  - '@tailwindcss/oxide'
  - '@vscode/vsce-sign'
  - esbuild
  - keytar
  - sharp
  - workerd

overrides:
  '@mindcontrol/code-parser-wasm': workspace:*
  '@mindcontrol/code-types': workspace:*
  '@mindcontrol/vscode-sync': workspace:*
  '@mindcontrol/vscode-types': workspace:*
