packages:
  - vscode/extension
  - vscode/webview
  - parser
  - parser/pkg
  - types/pkg/ts

onlyBuiltDependencies:
  - "@vscode/vsce-sign"
  - esbuild
  - keytar

overrides:
  "@mindcontrol/code-parser": "workspace:*"
  "@mindcontrol/code-types": "workspace:*"
